// This file is auto-generated by @hey-api/openapi-ts

export const SignUpReqBodySchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
  required: ["email", "password"],
} as const;

export const CommonResponseDtoSchema = {
  type: "object",
  properties: {
    statusCode: {
      type: "number",
    },
    message: {
      type: "string",
    },
    data: {
      type: "object",
    },
  },
  required: ["statusCode", "message", "data"],
} as const;

export const ErrorResponseDtoSchema = {
  type: "object",
  properties: {
    statusCode: {
      type: "number",
    },
    message: {
      type: "string",
    },
    error: {
      type: "string",
    },
    timestamp: {
      type: "string",
    },
    path: {
      type: "string",
    },
  },
  required: ["statusCode", "message", "error", "timestamp", "path"],
} as const;
