// This file is auto-generated by @hey-api/openapi-ts

export const SignUpSchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
  required: ["email", "password"],
} as const;
