// This file is auto-generated by @hey-api/openapi-ts

export const SignUpReqBodySchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
  required: ["email", "password"],
} as const;

export const SignUpSchema = {
  type: "object",
  properties: {
    aud: {
      type: "string",
    },
    email: {
      type: "string",
    },
    id: {
      type: "string",
    },
    created_at: {
      type: "string",
    },
    updated_at: {
      type: "string",
    },
    user_metadata: {
      type: "object",
    },
  },
  required: ["aud", "email", "id", "created_at", "updated_at", "user_metadata"],
} as const;

export const ErrorResponseSchema = {
  type: "object",
  properties: {
    statusCode: {
      type: "number",
    },
    message: {
      type: "string",
    },
  },
  required: ["statusCode", "message"],
} as const;

export const LoginReqBodySchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
  required: ["email", "password"],
} as const;

export const LoginSchema = {
  type: "object",
  properties: {
    aud: {
      type: "string",
    },
    email: {
      type: "string",
    },
    id: {
      type: "string",
    },
    created_at: {
      type: "string",
    },
    updated_at: {
      type: "string",
    },
    user_metadata: {
      type: "object",
    },
  },
  required: ["aud", "email", "id", "created_at", "updated_at", "user_metadata"],
} as const;

export const ProfileSchema = {
  type: "object",
  properties: {
    aud: {
      type: "string",
    },
    email: {
      type: "string",
    },
    id: {
      type: "string",
    },
    created_at: {
      type: "string",
    },
    updated_at: {
      type: "string",
    },
    user_metadata: {
      type: "object",
    },
  },
  required: ["aud", "email", "id", "created_at", "updated_at", "user_metadata"],
} as const;
