// This file is auto-generated by @hey-api/openapi-ts

export type SignUp = {
  email: string;
  password: string;
};

export type AppControllerGetHelloResponse = unknown;

export type AppControllerGetHelloError = unknown;

export type HealthControllerGetHealthResponse = unknown;

export type HealthControllerGetHealthError = unknown;

export type AuthControllerSignUpData = {
  body: SignUp;
};

export type AuthControllerSignUpResponse = unknown;

export type AuthControllerSignUpError = unknown;

export type AuthControllerMeResponse = unknown;

export type AuthControllerMeError = unknown;
