// This file is auto-generated by @hey-api/openapi-ts

export type CommonResponseDto = {
  statusCode: number;
  message: string;
  data: {
    [key: string]: unknown;
  };
};

export type ErrorResponseDto = {
  statusCode: number;
  message: string;
  error: string;
  timestamp: string;
  path: string;
};

export type SignUpReqBody = {
  email: string;
  password: string;
};

export type AppControllerGetHelloResponse = unknown;

export type AppControllerGetHelloError = unknown;

export type HealthControllerGetHealthResponse = unknown;

export type HealthControllerGetHealthError = unknown;

export type AuthControllerSignUpData = {
  body: SignUpReqBody;
};

export type AuthControllerSignUpResponse = CommonResponseDto;

export type AuthControllerSignUpError = ErrorResponseDto;

export type AuthControllerMeResponse = CommonResponseDto;

export type AuthControllerMeError = ErrorResponseDto;
