// This file is auto-generated by @hey-api/openapi-ts

export type ErrorResponse = {
  statusCode: number;
  message: string;
};

export type Login = {
  aud: string;
  email: string;
  id: string;
  created_at: string;
  updated_at: string;
  user_metadata: {
    [key: string]: unknown;
  };
};

export type LoginReqBody = {
  email: string;
  password: string;
};

export type Profile = {
  aud: string;
  email: string;
  id: string;
  created_at: string;
  updated_at: string;
  user_metadata: {
    [key: string]: unknown;
  };
};

export type SignUp = {
  aud: string;
  email: string;
  id: string;
  created_at: string;
  updated_at: string;
  user_metadata: {
    [key: string]: unknown;
  };
};

export type SignUpReqBody = {
  email: string;
  password: string;
};

export type AppControllerGetHelloResponse = unknown;

export type AppControllerGetHelloError = unknown;

export type HealthControllerGetHealthResponse = unknown;

export type HealthControllerGetHealthError = unknown;

export type AuthControllerSignUpData = {
  body: SignUpReqBody;
};

export type AuthControllerSignUpResponse = SignUp;

export type AuthControllerSignUpError = ErrorResponse;

export type AuthControllerLoginData = {
  body: LoginReqBody;
};

export type AuthControllerLoginResponse = Login;

export type AuthControllerLoginError = ErrorResponse;

export type AuthControllerProfileResponse = Profile;

export type AuthControllerProfileError = ErrorResponse;
