ALTER TABLE "profiles" DROP COLUMN IF EXISTS "instance_id";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "aud";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "role";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "encrypted_password";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "email_confirmed_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "invited_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "confirmation_token";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "confirmation_sent_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "recovery_token";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "recovery_sent_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "email_change_token_new";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "email_change";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "email_change_sent_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "last_sign_in_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "raw_app_meta_data";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "display_name";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "phone_confirmed_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "phone_change";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "phone_change_token";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "phone_change_sent_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "confirmed_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "email_change_token_current";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "email_change_confirm_status";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "banned_until";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "reauthentication_token";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "reauthentication_sent_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "is_sso_user";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "deleted_at";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN IF EXISTS "is_anonymous";