/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as authenticatedLayoutImport } from './routes/(authenticated)/_layout'
import { Route as authenticatedLayoutSscImport } from './routes/(authenticated)/_layout/ssc'
import { Route as authenticatedLayoutCreateChargepointImport } from './routes/(authenticated)/_layout/createChargepoint'
import { Route as authenticatedLayoutAbcImport } from './routes/(authenticated)/_layout/abc'

// Create Virtual Routes

const authenticatedImport = createFileRoute('/(authenticated)')()

// Create/Update Routes

const authenticatedRoute = authenticatedImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedLayoutRoute = authenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedLayoutSscRoute = authenticatedLayoutSscImport.update({
  id: '/ssc',
  path: '/ssc',
  getParentRoute: () => authenticatedLayoutRoute,
} as any)

const authenticatedLayoutCreateChargepointRoute =
  authenticatedLayoutCreateChargepointImport.update({
    id: '/createChargepoint',
    path: '/createChargepoint',
    getParentRoute: () => authenticatedLayoutRoute,
  } as any)

const authenticatedLayoutAbcRoute = authenticatedLayoutAbcImport.update({
  id: '/abc',
  path: '/abc',
  getParentRoute: () => authenticatedLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)/_layout': {
      id: '/(authenticated)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedLayoutImport
      parentRoute: typeof authenticatedRoute
    }
    '/(authenticated)/_layout/abc': {
      id: '/(authenticated)/_layout/abc'
      path: '/abc'
      fullPath: '/abc'
      preLoaderRoute: typeof authenticatedLayoutAbcImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/createChargepoint': {
      id: '/(authenticated)/_layout/createChargepoint'
      path: '/createChargepoint'
      fullPath: '/createChargepoint'
      preLoaderRoute: typeof authenticatedLayoutCreateChargepointImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/ssc': {
      id: '/(authenticated)/_layout/ssc'
      path: '/ssc'
      fullPath: '/ssc'
      preLoaderRoute: typeof authenticatedLayoutSscImport
      parentRoute: typeof authenticatedLayoutImport
    }
  }
}

// Create and export the route tree

interface authenticatedLayoutRouteChildren {
  authenticatedLayoutAbcRoute: typeof authenticatedLayoutAbcRoute
  authenticatedLayoutCreateChargepointRoute: typeof authenticatedLayoutCreateChargepointRoute
  authenticatedLayoutSscRoute: typeof authenticatedLayoutSscRoute
}

const authenticatedLayoutRouteChildren: authenticatedLayoutRouteChildren = {
  authenticatedLayoutAbcRoute: authenticatedLayoutAbcRoute,
  authenticatedLayoutCreateChargepointRoute:
    authenticatedLayoutCreateChargepointRoute,
  authenticatedLayoutSscRoute: authenticatedLayoutSscRoute,
}

const authenticatedLayoutRouteWithChildren =
  authenticatedLayoutRoute._addFileChildren(authenticatedLayoutRouteChildren)

interface authenticatedRouteChildren {
  authenticatedLayoutRoute: typeof authenticatedLayoutRouteWithChildren
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedLayoutRoute: authenticatedLayoutRouteWithChildren,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/abc': typeof authenticatedLayoutAbcRoute
  '/createChargepoint': typeof authenticatedLayoutCreateChargepointRoute
  '/ssc': typeof authenticatedLayoutSscRoute
}

export interface FileRoutesByTo {
  '/': typeof authenticatedLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/abc': typeof authenticatedLayoutAbcRoute
  '/createChargepoint': typeof authenticatedLayoutCreateChargepointRoute
  '/ssc': typeof authenticatedLayoutSscRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/(authenticated)': typeof authenticatedRouteWithChildren
  '/(authenticated)/_layout': typeof authenticatedLayoutRouteWithChildren
  '/(authenticated)/_layout/abc': typeof authenticatedLayoutAbcRoute
  '/(authenticated)/_layout/createChargepoint': typeof authenticatedLayoutCreateChargepointRoute
  '/(authenticated)/_layout/ssc': typeof authenticatedLayoutSscRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/abc' | '/createChargepoint' | '/ssc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/abc' | '/createChargepoint' | '/ssc'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/(authenticated)'
    | '/(authenticated)/_layout'
    | '/(authenticated)/_layout/abc'
    | '/(authenticated)/_layout/createChargepoint'
    | '/(authenticated)/_layout/ssc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  authenticatedRoute: typeof authenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  authenticatedRoute: authenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/signup",
        "/(authenticated)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/(authenticated)": {
      "filePath": "(authenticated)",
      "children": [
        "/(authenticated)/_layout"
      ]
    },
    "/(authenticated)/_layout": {
      "filePath": "(authenticated)/_layout.tsx",
      "parent": "/(authenticated)",
      "children": [
        "/(authenticated)/_layout/abc",
        "/(authenticated)/_layout/createChargepoint",
        "/(authenticated)/_layout/ssc"
      ]
    },
    "/(authenticated)/_layout/abc": {
      "filePath": "(authenticated)/_layout/abc.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/createChargepoint": {
      "filePath": "(authenticated)/_layout/createChargepoint.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/ssc": {
      "filePath": "(authenticated)/_layout/ssc.tsx",
      "parent": "/(authenticated)/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
